# Google Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: marketing-analytics-mcp
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/marketing-analytics-mcp:latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-oauth-credentials
              key: client_id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth-credentials
              key: client_secret
        - name: GOOGLE_ADS_DEVELOPER_TOKEN
          valueFrom:
            secretKeyRef:
              name: google-ads-credentials
              key: developer_token
        - name: GA4_PROPERTY_ID
          value: "YOUR_GA4_PROPERTY_ID"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {}

---
# Deploy with:
# gcloud run services replace gcp-cloud-run.yaml --region=us-central1